### ISSUE TITLE
what's the display

### ISSUE THREAD

**Issue by wsrajesh** [Anaisdg/Influx_Pandas#2]
#in your query there is a function named display which is not written in script, and when i am calling the api query it is returning me blank data, could you help me with this

client = InfluxDBClient(url="http://localhost:9999", token=my_token, org=my_org, debug=False)

system_stats = client.query_api().query_data_frame(org=my_org, query=query)
**display**(system_stats.head())

**Comment by Anaisdg** [comment]
Hello @wsgoldy, 
Thanks for letting me know. I removed that line. It should just be `system_stats.head()`
